### ISSUE TITLE
Hosts go offine and then online every few seconds

### ISSUE THREAD

**Issue by ski7111** [basildane/WakeOnLAN#77]
I have several host running, every minutes or less one will drop offline and then back online. what can cause this?

**Comment by basildane** [comment]
What version are you running?  This should have been fixed in .18 released a few weeks ago.

**Comment by ski7111** [comment]
Looks like the issue is still there. 

    On Wednesday, August 2, 2017 7:02 PM, Basildane <notifications@github.com> wrote:
 

 What version are you running? This should have been fixed in .18 released a few weeks ago.—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.  

   

|  | Virus-free. www.avast.com  |

**Comment by basildane** [comment]
Could you open WOL, turn OFF the pinger.
Start the debug log.  Tools -> Debug log.
Turn ON the pinger.

copy the debug log text and email it to me at basildane@aquilatech.com

You are running 2.11.18?
